# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="nicecontent" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="1.0.0" #mandatory
 # A display name for the mod
displayName="Nice Content" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Thanks Forge 43.1.1 for this mod" #optional
# A text field displayed in the mod UI
authors="Array64" #optional
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''
This is a mod which includes some random stuff, for fun
but also has some helpful things.
What's added:
1) Drunk effect (wobbles your movement) and Creeperness (generates explosion)
2) Vodka (A potion for Drunk effect) and Creeperness potion (Two variants: Normal and Strong)
Vodka is made by brewing a water bottle with an apple, and Creeperness is made by brewing an awkward potion with a gunpowder block. (3)
There are four variants: Vodka, Grass Vodka, Poisonous Potato Vodka, and Grass Poisonous Potato Vodka
To get Grass/Poisonous Potato Vodka, brew Vodka with Grass/A Poisonous Potato respectively.
To get Grass Poisonous Potato Vodka, just brew Grass Vodka with a Poisonous Potato
or Poisonous Potato Vodka with Grass. The added effects can be seen in game.
3) Gunpowder blocks: Just like diamond blocks, these can be crafted or uncrafted with 9 gunpowder. They need a wooden tool to drop. [Creative Mode Tab: Building Blocks]
4) Player Data GUI: Armor, health, hunger, saturation and exhaustion are now clearly displayed beside the vanilla GUI.
5) Grenades: Explode on impact [Creative Mode Tab: Combat]
Crafting Recipe:

323
212
323

(1 = Block of Gunpowder, 2 = Iron Ingot, 3 = Cobblestone)

6) Explosion resistance [Creative Mode Tab: Combat]
When held in main hand or offhand, you don't take damage from explosions.
You still take knockback, though. Since this item is too overpowered,
there is no crafting recipe for it, meaning you cannot get it in pure survival.

7) Comeback Enchantment; It's like Thorns, but it only works
if someone critically attacks you. It also breaks 1.5x slower
than thorns. Custom death messages for dying because of the Comeback enchantment.
The aim of this Enchantment is to give others a disadvantage of crit-spamming you.

8) death.fell.accident.water has now been renamed to "Player fell on a waterlogged block"
9) The Trident Sword [Creative Mode Tab: Combat]
It's a trident that can support Sword Enchantments, but not Riptide or Impaling.
The sword has 1.8 attack speed, 6.5 attack damage, but only 150 durability.
Hence, Unbreaking becomes critical for this weapon. Its ranged attack is also 6.5 damage.
To get it, combine an trident with an iron ingot in a smithing table.
You will get 2 trident swords instead of one.

10) Reach display: The top left corner now shows the minimum reach your opponent requires to attack you.
It is changed when you attack your opponent. It is not rare to get a reading of 3+ blocks, if you have
the low ground.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nicecontent]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.nicecontent]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)" # 1.19.3's Creative Mode Tab system has changed.
    ordering="NONE"
    side="BOTH"
